// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.PreviousRoundView = (function(_super) {
    __extends(PreviousRoundView, _super);

    function PreviousRoundView() {
      return PreviousRoundView.__super__.constructor.apply(this, arguments);
    }

    PreviousRoundView.prototype.className = 'previous-round';

    PreviousRoundView.prototype.template = _.template('<h2><% if(isDealer){ %>Dealer<% }else{ %>You<% } %> (<span class="score"></span>)</h2>');

    PreviousRoundView.prototype.initialize = function() {
      debugger;
      var array;
      array = this.collection.map(function(card) {
        return console.log('card', card);
      });
      this.collection.on('win lose', (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      return this.render();
    };

    PreviousRoundView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.html(this.template(this.collection));
      this.$el.append(this.collection.map(function(card) {
        return card.$el;
      }));
      return this.$('.score').text(this.collection.scores());
    };

    return PreviousRoundView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=PreviousRoundView.map
