// Generated by CoffeeScript 1.7.1
(function() {
  var assert, expect;

  assert = chai.assert;

  expect = chai.expect;

  describe('app', function() {
    var app, deck, hand;
    app = null;
    deck = null;
    hand = null;
    beforeEach(function() {});
    describe('Manually set hands', function() {
      return it("should expect dealer score to equal 8", function() {
        app = new AppView({
          model: new App()
        });
        app.model.get('dealerHand').models[0].set('value', 3);
        app.model.get('dealerHand').models[1].set('value', 5);
        return expect(app.model.get('dealerHand').scores()[0]).to.equal(8);
      });
    });
    describe('Automatically start dealer play', function() {
      return it("should automatically play the dealer's hand when user stands and dealer's score is under 17", function() {
        app = new AppView({
          model: new App()
        });
        app.model.get('playerHand').models[0].set('value', 10);
        app.model.get('playerHand').models[1].set('value', 7);
        app.model.get('dealerHand').models[0].set('value', 3);
        app.model.get('dealerHand').models[1].set('value', 5);
        app.model.get('playerHand').stand();
        return expect(app.model.get('dealerHand').length).to.be.at.least(3);
      });
    });
    describe('Dealer Win', function() {
      return it("should award win to dealer if dealer's score is to 21 and neither have busted", function() {
        app = new AppView({
          model: new App()
        });
        console.log('playerHand1', app.model.get('playerHand'));
        app.model.get('playerHand').models[0].set('value', 10);
        app.model.get('playerHand').models[1].set('value', 7);
        console.log('playerHand2', app.model.get('playerHand'));
        console.log('dealerHand1', app.model.get('dealerHand'));
        app.model.get('dealerHand').models[0].set({
          'value': 10,
          'revealed': true
        });
        app.model.get('dealerHand').models[1].set('value', 1);
        console.log(app.model.get('dealerHand').scores(), app.model.get('playerHand').scores());
        return assert.strictEqual(app.model.compareScores(), 'you lose');
      });
    });
    describe('User Win', function() {
      return it("should award win to user if user's score is closest to 21 and neither have busted", function() {
        return assert.strictEqual(app.model.compareScores(), void 0);
      });
    });
    describe('Dealer Hit', function() {
      return it("should keep hitting until dealer has a score greater than or equal to 17", function() {
        return assert.strictEqual(app.model.compareScores(), void 0);
      });
    });
    return describe('Dealer Bust', function() {
      return it("should stop hitting dealer's hand when they've busted", function() {
        return assert.strictEqual(app.model.compareScores(), void 0);
      });
    });
  });

}).call(this);

//# sourceMappingURL=BlackjackViewSpec.map
