// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.PreviousRounds = (function(_super) {
    __extends(PreviousRounds, _super);

    function PreviousRounds() {
      return PreviousRounds.__super__.constructor.apply(this, arguments);
    }

    PreviousRounds.prototype.model = PreviousRound;

    PreviousRounds.prototype.localStorage = new Backbone.LocalStorage("PreviousRounds");

    PreviousRounds.prototype.initialize = function() {
      return this.on('add', (function(_this) {
        return function(round) {
          return console.log('this', _this);
        };
      })(this));
    };

    return PreviousRounds;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=PreviousRounds.map
